kind: pipeline
name: default

steps:
- name: build
  image: java
  commands:
  - echo "Hello world desde build"
  when:
  event:
  - push
- name: deploy_to_prod
  image: java
  commands:
  - echo "Hello world desde prod"
  when:
    event:
      - promote
    target:
      - prod