kind: pipeline
name: default

steps:
- name: publish
  image: java
  commands:
  - echo "Hello world desde build"
  when:
    ref: [ refs/tags/v*]
    event: [ tag ]
- name: deploy_to_prod
  image: java
  commands:
  - echo "Hello world desde prod"
  when:
    ref: [ refs/tags/release-v*]
    event: [ tag ]