kind: pipeline
name: default

steps:
- name: build
  image: java
  commands:
  - javac src/com/twu/intro/*.java
  when:
  event:
  - push
- name: test
  image: java
  commands:
  - java PrimeFactorsTests
  detach: true